### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by YongFuYeAccount** [agrija9/Deep-Unsupervised-Domain-Adaptation#4]
Can you provide data set documentation

**Comment by agrija9** [comment]
@YongFuYeAccount We provide a brief description of the dataset here: https://arxiv.org/pdf/2109.13420.pdf. 

You can download it here (Downloads/Datasets section): https://faculty.cc.gatech.edu/~judy/domainadapt/.

**Comment by agrija9** [comment]
I will close this issue as it appears to be that my reply is informative enough.
